name: Build and deploy Node.js app to Azure Web App - hg-backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (backend)
        run: npm ci
        working-directory: apps/backend

      - name: Build (backend)
        run: npm run build
        working-directory: apps/backend

      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-zip
          path: .

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4C93251DEACB4D10A5B23FE1CD7D93F2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_46843AC4110A41FBAD73DDB6865B0709 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EDBE6C353E1E477DAE3FE624581B3052 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: hg-backend
          slot-name: Production
          package: backend.zip
